# Generated by Django 4.1.4 on 2023-01-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskogotchi',
            options={'verbose_name': 'Taskogotchi', 'verbose_name_plural': 'Taskogotchies'},
        ),
        migrations.AlterField(
            model_name='fightchallenge',
            name='status',
            field=models.CharField(choices=[('WA', 'Waiting for accept'), ('P', 'Pending'), ('CO', 'Completed'), ('CA', 'Canceled')], default='WA', max_length=2),
        ),
    ]
