# Generated by Django 4.1.4 on 2023-01-07 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fightchallenge',
            options={'verbose_name': 'Fight', 'verbose_name_plural': 'Fights'},
        ),
        migrations.AlterModelOptions(
            name='taskogotchi',
            options={'verbose_name': 'Taskogotchi', 'verbose_name_plural': 'Taskogotchies'},
        ),
        migrations.AlterField(
            model_name='fightchallenge',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_fights', to='core.playerprofile'),
        ),
        migrations.AlterField(
            model_name='fightchallenge',
            name='status',
            field=models.CharField(choices=[('WA', 'Waiting for accept'), ('AC', 'Accepted'), ('P', 'Pending'), ('CO', 'Completed'), ('CA', 'Canceled')], default='WA', max_length=2),
        ),
        migrations.AddConstraint(
            model_name='fightchallenge',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('draw', True), models.Q(('winner__isnull', False), ('status', 'CO')), _connector='XOR'), models.Q(('draw', False), ('winner__isnull', True), models.Q(('status', 'CO'), _negated=True)), _connector='OR'), name='draw_and_winner__isnull_not_equal', violation_error_message='Draw and winner__isnull must be not set until fight is not completed. When completed, draw and winner must not be equal'),
        ),
    ]
