# Generated by Django 4.1.4 on 2023-01-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_fightchallenge_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fightchallenge',
            name='draw_and_winner__isnull_not_equal',
        ),
        migrations.AddField(
            model_name='fightchallenge',
            name='initiator_health',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='fightchallenge',
            name='initiator_strength',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='fightchallenge',
            name='opponent_health',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='fightchallenge',
            name='opponent_strength',
            field=models.IntegerField(default=100),
        ),
        migrations.AddConstraint(
            model_name='fightchallenge',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('draw', True), models.Q(('winner__isnull', False), ('status', 'CO')), _connector='XOR'), models.Q(('draw', False), ('winner__isnull', True), models.Q(('status', 'CO'), _negated=True)), _connector='OR'), name='draw_and_winner__isnull_not_equal', violation_error_message='Draw and winner must be not set until fight is not completed. When completed, draw and winner must not be equal'),
        ),
    ]
